# DO NOT EDIT THIS FILE!
#
# Python module rtcControl__POA generated by omniidl

import omniORB
omniORB.updateModule("rtcControl__POA")

# ** 1. Stub files contributing to this module
import rtcControl_idl

# ** 2. Sub-modules

# ** 3. End
