cd /d %~dp0
cmd /c AccAndMagnSensor_LSM303DLHC\BuildDebug.bat
cmd /c AccelerationSensor_KXR94_2050\BuildDebug.bat
cmd /c AccelerationSensor_KXSC7_2050\BuildDebug.bat
cmd /c Adafruit_PWMServoDriver_Edison\BuildDebug.bat
cmd /c ADC_Edison\BuildDebug.bat
cmd /c ADC_MCP3002\BuildDebug.bat
cmd /c ADC_MCP3208\BuildDebug.bat
cmd /c CrawlerControllerPWM2\BuildDebug.bat
cmd /c DigitalOutput_Edison\BuildDebug.bat
cmd /c GyroSensor_ENC_03R\BuildDebug.bat
cmd /c GyroSensor_L3GD20_I2C\BuildDebug.bat
cmd /c MotorDriver_TA7291P\BuildDebug.bat
cmd /c MotorDriver_TA8428K\BuildDebug.bat
cmd /c NineAxisSensor_LSM9DS0_I2C\BuildDebug.bat
cmd /c PWM_Edison\BuildDebug.bat
cmd /c RangeSensor_GP2Y0A21YK\BuildDebug.bat
cmd /c temperatureSensor_ADT7410\BuildDebug.bat
cmd /c CrawlerController\BuildDebug.bat
cmd /c RobotArmController\BuildDebug.bat
