cd /d %~dp0
cmd /c AccAndMagnSensor_LSM303DLHC\BuildRelease.bat
cmd /c AccelerationSensor_KXR94_2050\BuildRelease.bat
cmd /c AccelerationSensor_KXSC7_2050\BuildRelease.bat
cmd /c Adafruit_PWMServoDriver_Edison\BuildRelease.bat
cmd /c ADC_Edison\BuildRelease.bat
cmd /c ADC_MCP3002\BuildRelease.bat
cmd /c ADC_MCP3208\BuildRelease.bat
cmd /c CrawlerControllerPWM2\BuildRelease.bat
cmd /c DigitalOutput_Edison\BuildRelease.bat
cmd /c GyroSensor_ENC_03R\BuildRelease.bat
cmd /c GyroSensor_L3GD20_I2C\BuildRelease.bat
cmd /c MotorDriver_TA7291P\BuildRelease.bat
cmd /c MotorDriver_TA8428K\BuildRelease.bat
cmd /c NineAxisSensor_LSM9DS0_I2C\BuildRelease.bat
cmd /c PWM_Edison\BuildRelease.bat
cmd /c RangeSensor_GP2Y0A21YK\BuildRelease.bat
cmd /c temperatureSensor_ADT7410\BuildRelease.bat
cmd /c CrawlerController\BuildRelease.bat
cmd /c RobotArmController\BuildRelease.bat
