cd /d %~dp0
cmd /c AccAndMagnSensor_LSM303DLHC\Install.bat
cmd /c AccelerationSensor_KXR94_2050\Install.bat
cmd /c AccelerationSensor_KXSC7_2050\Install.bat
cmd /c Adafruit_PWMServoDriver_Edison\Install.bat
cmd /c ADC_Edison\Install.bat
cmd /c ADC_MCP3002\Install.bat
cmd /c ADC_MCP3208\Install.bat
cmd /c CrawlerControllerPWM2\Install.bat
cmd /c DigitalOutput_Edison\Install.bat
cmd /c GyroSensor_ENC_03R\Install.bat
cmd /c GyroSensor_L3GD20_I2C\Install.bat
cmd /c MotorDriver_TA7291P\Install.bat
cmd /c MotorDriver_TA8428K\Install.bat
cmd /c NineAxisSensor_LSM9DS0_I2C\Install.bat
cmd /c PWM_Edison\Install.bat
cmd /c RangeSensor_GP2Y0A21YK\Install.bat
cmd /c temperatureSensor_ADT7410\Install.bat
cmd /c CrawlerController\Install.bat
cmd /c RobotArmController\Install.bat
