cd /d %~dp0
cmd /c AccAndMagnSensor_LSM303DLHC\unInstall.bat
cmd /c AccelerationSensor_KXR94_2050\unInstall.bat
cmd /c AccelerationSensor_KXSC7_2050\unInstall.bat
cmd /c Adafruit_PWMServoDriver_Edison\unInstall.bat
cmd /c ADC_Edison\unInstall.bat
cmd /c ADC_MCP3002\unInstall.bat
cmd /c ADC_MCP3208\unInstall.bat
cmd /c CrawlerControllerPWM2\unInstall.bat
cmd /c DigitalOutput_Edison\unInstall.bat
cmd /c GyroSensor_ENC_03R\unInstall.bat
cmd /c GyroSensor_L3GD20_I2C\unInstall.bat
cmd /c MotorDriver_TA7291P\unInstall.bat
cmd /c MotorDriver_TA8428K\unInstall.bat
cmd /c NineAxisSensor_LSM9DS0_I2C\unInstall.bat
cmd /c PWM_Edison\unInstall.bat
cmd /c RangeSensor_GP2Y0A21YK\unInstall.bat
cmd /c temperatureSensor_ADT7410\unInstall.bat
cmd /c CrawlerController\unInstall.bat
cmd /c RobotArmController\unInstall.bat
