# DO NOT EDIT THIS FILE!
#
# Python module RTCConfData generated by omniidl

import omniORB
omniORB.updateModule("RTCConfData")

# ** 1. Stub files contributing to this module
import rtcconf_idl

# ** 2. Sub-modules

# ** 3. End
