# DO NOT EDIT THIS FILE!
#
# Python module RTCConfData__POA generated by omniidl

import omniORB
omniORB.updateModule("RTCConfData__POA")

# ** 1. Stub files contributing to this module
import rtcconf_idl

# ** 2. Sub-modules

# ** 3. End
